- name: Load audit rules
  ansible.builtin.command: augenrules --load
  changed_when: true
  notify: Restart audit service

- name: Restart audit service
  ansible.builtin.command: service auditd restart
  ignore_errors: true