# -----------------------------------------------------------------------------
# Testing
# -----------------------------------------------------------------------------

[monitor:///tmp/test.log]
index = linux
sourcetype = test
crcSalt = <SOURCE>

# -----------------------------------------------------------------------------
# System, Kernel, & Package Management
# -----------------------------------------------------------------------------

[monitor:///var/log/auth.log]
index = linux
sourcetype = linux_secure
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$
 
[monitor:///var/log/secure]
index = linux
sourcetype = linux_secure
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$
 
[monitor:///var/log/messages]
index = linux
sourcetype = syslog
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$
 
[monitor:///var/log/syslog]
index = linux
sourcetype = syslog
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$
 
[monitor:///var/log/kern.log]
index = linux
sourcetype = linux_kernel
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$
 
[monitor:///var/log/cron]
index = linux
sourcetype = cron
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$
 
[monitor:///var/log/yum.log]
index = linux
sourcetype = package
crcSalt = <SOURCE>
 
[monitor:///var/log/apt/history.log]
index = linux
sourcetype = package
crcSalt = <SOURCE>

# -----------------------------------------------------------------------------
# Security Services (Audit, Firewall, IDS, etc.)
# -----------------------------------------------------------------------------
 
[monitor:///var/log/audit/audit.log]
index = linux
sourcetype = linux:audit
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$

[monitor:///var/log/ufw.log]
index = linux
sourcetype = linux:ufw
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$

[monitor:///var/log/firewalld]
index = linux
sourcetype = linux:firewalld
crcSalt = <SOURCE>

# -----------------------------------------------------------------------------
# Scored Services
# -----------------------------------------------------------------------------
 
[monitor:///var/log/apache2/access.log]
index = services
sourcetype = apache:access
crcSalt = <SOURCE>
 
[monitor:///var/log/apache2/error.log]
index = services
sourcetype = apache:error
crcSalt = <SOURCE>

[monitor:///var/log/apache2/opencart-access-log]
index = services
sourcetype = apache:access
crcSalt = <SOURCE>
 
[monitor:///var/log/apache2/opencart-error-log]
index = services
sourcetype = apache:error
crcSalt = <SOURCE>

[monitor:///var/log/mysql/error.log]
index = services
sourcetype = mysql:errorLog
crcSalt = <SOURCE>
 
[monitor:///var/log/maillog]
index = services
sourcetype = linux:maillog
crcSalt = <SOURCE>
blacklist = \.(gz|bz2|zip)$|\.\d$
