# -----------------------------------------------------------------------------
# Testing
# -----------------------------------------------------------------------------

[monitor://C:\temp\test.log]
disabled = 0
index = windows
sourcetype = test

# -----------------------------------------------------------------------------
# Standard Windows Event Logs
# -----------------------------------------------------------------------------

[WinEventLog://Application]
disabled = 0
index = windows

[WinEventLog://Security]
disabled = 0
index = windows

[WinEventLog://System]
disabled = 0
index = windows

# -----------------------------------------------------------------------------
# Security Services (Defender, Sysmon)
# -----------------------------------------------------------------------------

[WinEventLog://Microsoft-Windows-Windows Defender/Operational]
disabled = 0
index = windows
sourcetype = WinEventLog:Defender

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = windows
sourcetype = WinEventLog:Sysmon

# -----------------------------------------------------------------------------
# Additional Lateral Movement (WinRM, WMI, SMB, AtExec)
# -----------------------------------------------------------------------------

[WinEventLog://Microsoft-Windows-PowerShell/Operational]
disabled = 0
index = windows
sourcetype = WinEventLog:PowerShell

[WinEventLog://Microsoft-Windows-WinRM/Operational]
disabled = 0
index = windows
sourcetype = WinEventLog:WinRM

[WinEventLog://Microsoft-Windows-WMI-Activity/Operational]
disabled = 0
index = windows
sourcetype = WinEventLog:WMI

[WinEventLog://Microsoft-Windows-SMBServer/Operational]
disabled = 0
index = windows
sourcetype = WinEventLog:WMI

[WinEventLog://Microsoft-Windows-TaskScheduler/Operational]
disabled = 0
index = windows
sourcetype = WinEventLog:TaskScheduler

# -----------------------------------------------------------------------------
# Scored Services
# -----------------------------------------------------------------------------

# This doesn't work :(
[WinEventLog://Microsoft-Windows-DNSServer/Analytical]
disabled = 0
index = services
renderXml = 1
sourcetype = msdns:analytical

[monitor://C:\Windows\System32\dns\dns*.log]
disabled = 0
index = services
sourcetype = ms:dns:debug

[monitor://C:\inetpub\logs\LogFiles\W3SVC*\*.log]
disabled = 0
index = services
sourcetype = ms:iis:auto

[monitor://C:\inetpub\logs\LogFiles\FTPSVC*\*.log]
disabled = 0
index = services
sourcetype = ms:iis:auto
